### ISSUE TITLE
To much tabs!

### ISSUE THREAD

**Issue by ghost** [fastaddons/PrivateNotes#15]
Hi, notification window to enter password (for check if remember), appear in multiple tabs! please make verification to not open another tabs if one tab already oppened!
![image](https://user-images.githubusercontent.com/20506433/155842834-8d35e6ce-5981-4bc9-a76a-c4d0342d1d12.png)

**Comment by fastaddons** [comment]
Interesting... there is already a check to see if the addon is already running, but I guess in this case those tabs are unloaded (discarded) so the script is not running inside.
Do you use some addon for unloading or discarding inactive tabs?

**Comment by ghost** [comment]
hi, yes, i use tab unloader :) i adden in never auto unload, thanks!

**Comment by fastaddons** [comment]
Thanks for the info!
Although it's still not great. I think I can make it better by scheduling a single specific reminder instead of checking the time every 30 min like I'm doing now.
Thank you for pointing this out!
